[package]
name = "lwk_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jade = { path = "../jade", features = ["serial"] }
jsonrpc = "0.17.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
secp256k1 = "0.27"
signer = { path = "../signer" }
tiny_jrpc = { path = "../tiny_jrpc" }
thiserror = "1"
tracing = "0.1"
lwk_common = { path = "../lwk_common" }
rpc_model = { path = "../rpc_model" }
wollet = { path = "../wollet" }
rand = "0.8.5"
schemars = "0.8.16"
home = "0.5.5"

[dev-dependencies]
enum-iterator = "1.4.1"
tempfile = "3.8.1"
