[package]
name = "jade"
version = "0.1.0"
edition = "2021"

[dependencies]
# anyhow = "1"
ciborium = "0.2.1"
hex = "0.4.3"
rand = "0.8.5"
# reqwest = { version = "0.11.19", features = ["blocking", "json"] }
serde = "1"
serde_bytes = "0.11.12"
# serde_json = "1"
serialport = { version = "4.2.1", optional = true }
thiserror = "1"
ureq = { version = "2.7.1", features = ["json"] }
# tokio = { version = "1.32.0", features = ["rt", "macros"] }
# tracing = "0.1.37"
# tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[features]
serial = ["serialport"]

[[test]]
name = "emulator"
path = "test/emulator.rs"

[[test]]
name = "serial"
path = "test/serial.rs"

[[test]]
name = "pin_server"
path = "test/pin_server.rs"

[dev-dependencies]
bitcoin = "0.30.1"
insta = { version = "1.31.0", features = ["yaml"] }
tempfile = "3.8.0"
testcontainers = "0.14"
