[package]
name = "bs_containers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.31"
rand = "0.8.5"
tempfile = "3.8.0"
testcontainers = "0.14.0"
