[package]
name = "lwk_jade"
version = "0.1.0"
edition = "2021"
autotests = false

[dependencies]
# anyhow = "1"
serde_cbor = "0.11.2"
hex = "0.4.3"
rand = "0.8.5"
# reqwest = { version = "0.11.19", features = ["blocking", "json"] }
serde = "1"
serde_bytes = "0.11.12"
serde_json = "1"
elements = { version = "0.24.0", features = ["base64", "serde"] }
serialport = { version = "4.2.1", optional = true }
thiserror = "1"

tracing = "0.1"

minreq = { version = "2.9", features = ["https"] }
elements-miniscript = "0.2"

lwk_common = { path = "../lwk_common" }

# tokio = { version = "1.32.0", features = ["rt", "macros"] }


[features]
serial = ["serialport"]

[[test]]
name = "e2e"
path = "tests/e2e.rs"

[dev-dependencies]
tempfile = "3.8.0"
bs_containers = { path = "../bs_containers" }
base64 = "0.21.4"
serde_json = "1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
lwk_test_util = { path = "../lwk_test_util" }
