variables:
  CI_DISPOSABLE_ENVIRONMENT: "true"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

.base:
  image: rust:1.70
  tags:
    - cloud
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - stuck_or_timeout_failure

.docker:
  extends: .base
  before_script:
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - chmod a+r /etc/apt/keyrings/docker.gpg
    - echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | /usr/bin/tee /etc/apt/sources.list.d/docker.list > /dev/null
    - apt-get update
    - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin libudev-dev
  tags:
    - k8s-docker
  services:
    - docker:20.10.12-dind

fmt:
  extends: .base
  script:
    - rustup component add rustfmt
    - cargo fmt --check

clippy:
  extends: .base
  script:
    - rustup component add clippy
    - cargo clippy --all-targets -- -D warnings

build:
  extends: .base
  script:
    - cargo build

test_wollet:
  extends: .base
  script:
    - ./download_bins.sh
    - . .envrc
    - cargo test -p wollet -p software_signer

test_jade:
  extends: .docker
  script:
    - echo $DOCKER_TOKEN | docker login glregistry.blockstream.io -u $DOCKER_USER --password-stdin
    - docker pull glregistry.blockstream.io/byronhambly/jadeqemu:latest
    - cargo test -p jade

test_jrpc:
  extends: .base
  script:
    - cargo test -p tiny_jrpc

audit:
  extends: .base
  script:
    - cargo install cargo-audit
    - cargo audit -D warnings
