
.base:
  image: rust:1.70
  tags:
    - cloud
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - stuck_or_timeout_failure

fmt:
  extends: .base
  script:
    - rustup component add rustfmt
    - cargo fmt --check

build:
  extends: .base
  script:
    - cargo build

test:
  extends: .base
  script:
    - ./download_bins.sh
    - . .envrc
    - cargo test
