variables:
  CI_DISPOSABLE_ENVIRONMENT: "true"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

.base:
  image: xenoky/ks-builder@sha256:587bb253ed669e3390d45afd7aff989d954d8b6f64526111e64f36e59ac0f3fd
  tags:
    - cloud
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - stuck_or_timeout_failure  
  services:
    - docker:20.10.12-dind


fmt:
  extends: .base
  script:
    - cargo fmt --check

clippy:
  extends: .base
  script:
    - cargo clippy --all-targets -- -D warnings

build:
  extends: .base
  script:
    - cargo build --all-features --all-targets

test_wollet:
  extends: .base
  script:
    - docker pull xenoky/local-jade-emulator:1.0.23
    - cd / && . ./env.sh && cd -
    - cargo test -p wollet -p signer

test_jade:
  extends: .base
  script:
    - docker pull tulipan81/blind_pin_server:v0.0.3
    - docker pull xenoky/local-jade-emulator:1.0.23
    - cargo test -p jade

test_jrpc:
  extends: .base
  script:
    - cargo test -p tiny_jrpc

test_app:
  extends: .base
  script:
    - cargo test -p app

test_cli:
  extends: .base
  script:
    - cargo test -p cli

build_cli:
  extends: .base
  script:
    - cargo build --release -p cli
  artifacts:
    paths:
      - target/release/cli
    when: always
    expire_in: 14 days

audit:
  extends: .base
  script:
    - cargo audit -D warnings
