fmt:
  image: rust:1.70
  script:
    - rustup component add rustfmt
    - cargo fmt

build:
  image: rust:1.70
  script:
    - cargo build

test:
  image: rust:1.70
  script:
    - ./download_bins.sh
    - . .envrc
    - cargo test
