variables:
  CI_DISPOSABLE_ENVIRONMENT: "true"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_TLS_CERTDIR: ""

.base:
  image: xenoky/lwk-builder@sha256:511fa00c37fd3cb8aec7c250f6a3b94ed89f3baf1372b4951bb9568704a45e23
  tags:
    - cloud
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - stuck_or_timeout_failure  
  services:
    - docker:20.10.12-dind


fmt:
  extends: .base
  script:
    - cargo fmt --check
    - cargo clippy --all-targets -- -D warnings

test_wollet:
  extends: .base
  script:
    - docker pull xenoky/local-jade-emulator:1.0.23
    - cd / && . ./env.sh && cd -
    - cargo test -p lwk_wollet -p lwk_signer

test_jade:
  extends: .base
  script:
    - docker pull tulipan81/blind_pin_server:v0.0.3
    - docker pull xenoky/local-jade-emulator:1.0.23
    - cargo test -p lwk_jade

# run tests for minor crates all together
test_minor:
  extends: .base
  script:
    - cargo test -p lwk_tiny_jrpc -p lwk_app -p lwk_containers -p lwk_common -p lwk_hwi -p lwk_rpc_model -p lwk_signer

test_cli:
  extends: .base
  script:
    - cd / && . ./env.sh && cd -
    - cargo test -p lwk_cli

test_coverage:
  extends: .base
  variables:
    RUSTFLAGS: "-C instrument-coverage"
    LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"

  script:
    - docker pull tulipan81/blind_pin_server:v0.0.3
    - docker pull xenoky/local-jade-emulator:1.0.23
    - cd / && . ./env.sh && cd -
    - cargo nextest run --profile ci
    - grcov . -s . --binary-path ./target/debug/ -t cobertura --branch --ignore-not-existing --ignore "*cargo*" -o ./target/coverage.xml -p $(pwd)
    - "xmllint --xpath \"concat('Coverage: ', 100 * string(//coverage/@line-rate), ' perc')\" target/coverage.xml"
    - grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing --ignore "*cargo*" -o ./target/coverage/ -p $(pwd)
  coverage: '/Coverage: \d+(?:\.\d+)?/'
  artifacts:
    paths:
      - target/coverage.xml
      - target/coverage/
      - target/nextest/ci/junit.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: target/coverage.xml
      junit: target/nextest/ci/junit.xml

build_cli:
  extends: .base
  only:
    - master@liquid/lwk
  script:
    - cargo build --release -p lwk_cli
  artifacts:
    paths:
      - target/release/lwk_cli
    when: always
    expire_in: 14 days

audit:
  extends: .base
  script:
    # ignore unmantained serde_cbor
    - cargo audit -D warnings --ignore RUSTSEC-2021-0127

doc:
  extends: .base
  variables:
    RUSTDOCFLAGS: "-D warnings"
  script:
    - cargo doc --no-deps

bindings:
  extends: .base
  variables:
    LIB_EXT: "so"
  script:
    - just test-python-bindings

check_rust_170:
  extends: .base
  script:
    - cargo +1.70.0 check
