[workspace]

members = [
    "app",
    "cli",
    "hwi",
    "jade",
    "signer",
    "tiny_jrpc",
    "wollet",
    "bs_containers",
    "pset_common",
]
resolver = "2"


[patch.crates-io]
elements = { git = "https://github.com/ElementsProject/rust-elements.git", rev = "5d80b940f023f468afb981f090681cf8622d3933" }
jsonrpc = { git = "https://github.com/RCasatta/rust-jsonrpc", rev = "2c3f4622a5fe7df7b434d163267d4cb21d246cdd" }              # https://github.com/apoelstra/rust-jsonrpc/pull/108
