[package]
name = "bewallet"
version = "0.1.0"
authors = ["Riccardo Casatta <riccardo@casatta.it>", "Nadav Ivgi <nadav@shesek.info>", "William Casarin <jb55@jb55.com>", "Leonardo Comandini <leo@leocomandini.org>"]
license = "(MIT)"
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
rand = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11.1"
hex = "0.4.0"
log = "0.4.8"
aes-gcm-siv = "0.5.0"
electrum-client = "0.7.0"
secp256k1-zkp = { version = "0.3", features = [ "global-context", "hashes" ] }
bip39 = "1.0.0-rc1"

bitcoin = { version = "0.26", features = [ "use-serde" ] }
elements = { version = "0.16", features = ["serde-feature"] }

[dev-dependencies]
bitcoincore-rpc = "0.13"
chrono = "0.4.11"
tempdir = "0.3.7"

[profile.release]
lto = true
panic = 'abort'
opt-level = 'z'
codegen-units = 1
incremental = false
