[workspace]

members = ["hwi", "software_signer", "tiny_jrpc", "wollet"]
resolver = "2"


[patch.crates-io]
elements = { git = "https://github.com/ElementsProject/rust-elements.git", rev = "ca1b5c439c4fb7ad729909aa6a3deb7d4b2b1ce9" }
