[workspace]

members = [
    "hwi",
    "jade",
    "software_signer",
    "tiny_jrpc",
    "wollet",
    "bs_containers",
]
resolver = "2"


[patch.crates-io]
elements = { git = "https://github.com/ElementsProject/rust-elements.git", rev = "5d80b940f023f468afb981f090681cf8622d3933" }

[profile.dev.package."*"]
opt-level = 3
