[package]
name = "lwk_tiny_jrpc"
version = "0.1.0"
edition = "2021"
description = "Liquid Wallet Kit - Tiny JSON RPC Server"
license = "MIT OR BSD-2-Clause"
documentation = "https://docs.rs/lwk_tiny_jrpc"

[dependencies]
anyhow = "1.0.75"
jsonrpc = "0.17.0"
serde = "1.0.188"
serde_derive = "1.0.188"
serde_json = "1.0.106"
thiserror = "1"
tiny_http = "0.12.0"
tracing = "0.1"

[dev-dependencies]
minreq = "2.9"
tempfile = "3.8.0"
