[package]
name = "lwk_signer"
version = "0.1.0"
edition = "2021"
description = "Liquid Wallet Kit - Signers for PSETs (Partially Signed Elements Transactions)"
license = "MIT OR BSD-2-Clause"
documentation = "https://docs.rs/lwk_signer"

[dependencies]
bip39 = { version = "2.0.0", features = ["rand"] }
elements-miniscript = "0.3"
thiserror = "1.0.48"
base64 = "0.13.0"

lwk_common = { version = "0.2.0" }
lwk_jade = { path = "../lwk_jade" }

[dev-dependencies]
lwk_test_util = { path = "../lwk_test_util" }
