[package]
name = "lwk-bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
elements = "0.24.0"
thiserror = "1.0.50"
uniffi = { version = "0.26.0" }
wollet = { path = "../wollet" }
common = { path = "../common" }
signer = { path = "../signer" }
serde_json = "1"

[build-dependencies]
uniffi = { version = "0.26.0", features = ["build"] }

[lib]
crate-type = ["cdylib"]
name = "lwk_bindings"

[dev-dependencies]
test_util = { path = "../test_util" }
