[package]
name = "lwk_ledger"
version = "0.1.0"
edition = "2021"
description = "Liquid Wallet Kit - Interact with Ledger Hardware Wallet"
license = "MIT OR BSD-2-Clause"
documentation = "https://docs.rs/lwk_jade"

[dependencies]
ledger-apdu = "0.10"
elements-miniscript = { version = "0.3", features = ["serde"] }
lwk_common = "0.4"

[dev-dependencies]
lwk_containers = { version = "0.3.0" }
