[package]
name = "rpc_model"
version = "0.1.0"
edition = "2021"

[dependencies]
schemars = "0.8.16"
serde = { version = "1.0.193", features = ["derive"] }
# avoid deps to the workspace

[dev-dependencies]
serde_json = "1.0.108"
