[package]
name = "wollet"
version = "0.1.0"
authors = [
    "Riccardo Casatta <riccardo@casatta.it>",
    "Nadav Ivgi <nadav@shesek.info>",
    "William Casarin <jb55@jb55.com>",
    "Leonardo Comandini <leo@leocomandini.org>",
]
license = "(MIT)"
edition = "2018"
autotests = false

[lib]
crate-type = ["lib"]

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11.2"
aes-gcm-siv = "0.10.0"
electrum-client = "0.15.0"
bip39 = "2.0.0"
elements-miniscript = { version = "0.2", features = ["serde"] }
thiserror = "1.0.48"
once_cell = "1.18.0"
elements = { version = "0.23.0", features = ["base64"] }
common = { path = "../common" }

#registry
idna = "0.4.0"
regex = "1.9.6"

tracing = "0.1"

[dev-dependencies]
tempfile = "3.8.0"
signer = { path = "../signer" }
jade = { path = "../jade" }
bs_containers = { path = "../bs_containers" }
minreq = { version = "2.9", features = ["https"] }
test_util = { path = "../test_util" }

[features]
serial = ["jade/serial"]

[[test]]
name = "e2e"
path = "tests/e2e.rs"
