[package]
name = "wollet"
version = "0.1.0"
authors = [
    "Riccardo Casatta <riccardo@casatta.it>",
    "Nadav Ivgi <nadav@shesek.info>",
    "William Casarin <jb55@jb55.com>",
    "Leonardo Comandini <leo@leocomandini.org>",
]
license = "(MIT)"
edition = "2018"
autotests = false

[lib]
crate-type = ["lib"]

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ciborium = "0.2.1"
log = "0.4.8"
aes-gcm-siv = "0.10.0"
electrum-client = "0.15.0"
bip39 = "2.0.0"
elements-miniscript = { git = "https://github.com/ElementsProject/elements-miniscript.git", rev = "27b6e37af2cc850b20b5c4322b3673dcd452cd08", features = [
    "serde",
] }
thiserror = "1.0.48"
once_cell = "1.18.0"
elements = { version = "0.23.0", features = ["base64"] }

#registry
idna = "0.4.0"
regex = "1.9.6"

[dev-dependencies]
chrono = "0.4.11"
tempfile = "3.8.0"
electrsd = { version = "0.25.0", features = ["legacy"] }
software_signer = { path = "../software_signer" }
jade = { path = "../jade" }
bs_containers = { path = "../bs_containers" }


[[test]]
name = "e2e"
path = "tests/e2e.rs"
