on:
  push:
    branches:
      - master
  pull_request: {}

name: CI

jobs:

  cosmetics:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Cache
        uses: Swatinem/rust-cache@v1.2.0
      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt
      - name: Format
        run: cargo fmt -- --check

